### ISSUE TITLE
Minor UI issues

### ISSUE THREAD

**Issue by TheIceCreamTroll** [Kareadita/Kavita#1395]
**Describe the bug**
A collection of UI issues

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox
 - Version 0.5.4.14

- [ ] Down arrows are off-center from the circle
![offcenter](https://user-images.githubusercontent.com/33820904/184652531-cc1022c9-02fa-47ef-85d3-0d4ca7b22dc8.png)

- [ ] The color picker from User Settings > Image Reader displays the color code as black text on a dark grey background
![Color picker has black text on grey background](https://user-images.githubusercontent.com/33820904/182743958-34652103-d65b-4fb6-9fc9-dab32332693c.png)

- [ ] The outline of the return-to-top button clips through the search bar when the window is narrow enough
![outline clips search box](https://user-images.githubusercontent.com/33820904/182744271-9d612a10-eea8-4cce-aaa2-0258273e47d4.png)

- [ ] These two icons overlap
![Overlap](https://user-images.githubusercontent.com/33820904/182744553-08999280-1be4-4860-847f-8c1133353dc8.png)

- [ ] So do these. The username button is also slightly shorter than the server settings button.
![Different Outline Heights for user and settings  They also overlap](https://user-images.githubusercontent.com/33820904/182744577-ce0a3e19-6973-4a4c-92b3-7fa46e2a386c.png)

- [ ] Decreasing the width of the browser window causes these info boxes to eventually switch layouts, but not soon enough to prevent them from overlapping. The horizontal alignment of the elements also gets a bit wonky.
![When making a browser window smaller, this should probably switch to the grid layout sooner](https://user-images.githubusercontent.com/33820904/182744612-81c4c64a-ae01-43f9-b2b3-46a7ded97501.PNG)

- [ ] The grey highlight isn't consistent between the two buttons. The right arrow's highlight has its right side cut off.
![Wonky highight B](https://user-images.githubusercontent.com/33820904/182745018-48af6059-bae4-485b-80a0-b47bdaee82e2.png)
![Wonky highight A](https://user-images.githubusercontent.com/33820904/182745021-8cb9f4ff-ef54-4e44-b237-c46e34cd862d.png)

- [ ] On Firefox, the left side of these two buttons are cut off by 1 column of pixels. 
On Edge, they appear as expected. This is probably an issue on Firefox's end, as they appear as expected when I go to 180% zoom. Anything less, and the icons look as they do below.
![Left side is cut off by just a bit 2](https://user-images.githubusercontent.com/33820904/182745134-5c2b5d19-db94-4154-9319-87f5ac6ddef1.png)
![Left side is cut off by just a bit pic2](https://user-images.githubusercontent.com/33820904/182745137-24576d6a-463d-4d06-85ad-0cd7e681a6ac.png)
More info [here](https://medium.com/kajabi-ux/css-and-sub-pixel-rendering-the-case-of-the-clipped-border-4652c5a1b5ab)
and [here](https://stackoverflow.com/questions/34676263/sub-pixels-calculated-and-rendered-differently-among-browsers)

- [x] (#1407) "Blur Unread Summaries" should go under "Prompt on Download". Looks very odd in its current position.
![Blur Unread should go under Prompt on Download](https://user-images.githubusercontent.com/33820904/183239836-747853ad-ffb4-4c24-820a-5566e1cc8eef.png)

- [x] And clips the top of the window when bouncing
![Clips through the top of the top of the window](https://user-images.githubusercontent.com/33820904/182744441-57124f0d-29c3-4045-b8bd-3e928508ca0c.png)

- [x] (#1407) Assigned roles don't vertically align with the "Roles:" text
![Roles not centered to the semi-colon](https://user-images.githubusercontent.com/33820904/182744364-f9631e0b-02a3-4ded-a573-7c330b589843.PNG)

- [x] (#1407) Position of read time and word count are swapped
![5 1](https://user-images.githubusercontent.com/33820904/183255913-b280faf3-03d4-49e4-91d2-b61938ea6703.png)

**Comment by majora2007** [comment]
> The color picker from User Settings > Image Reader displays the color code as black text on a dark grey background

I know about this, I just left as is because it's minor. 

> Newly added series have the context menu, Recently Added Series do not.

This is per design

**Comment by HubKing** [comment]
The white on bright green button sucks for dark mode. It burns my eyes. The background colour should a darker green.

**Comment by majora2007** [comment]
@HubKing you can create your own theme. This is not the place for suggestions.
