### ISSUE TITLE
Comic Rework

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#2714]
The initial implementation of Comic support was built with limited exposure and limited input from community about Comics. Kavita has grown in size and as such, needs to rework the Comic support to align better with the needs of Comic users. 

This is a comprehensive story to tackle such an effort. 

### Series Grouping
- [x] Series will now be determined by Series Name + Volume number (year/number) from the first Volume
- [x] When metadata is not present, Kavita will fallback:
  - [x] First directory if it matches explicitly the format "Series (Year/VolumeNumber)"
  - [x] Check all directories up to root for the above
  - [x] Fallback to Directory name
- [x] Parallel series (DC Comics/Batman and DC Comics/Marvel) can still be a problem, each with the same run year. (This doesn't seem to be something that can easily be solved. I would opt for users to make a change and Kavita to write new information to the config about this situation)

### Misc
- [x] ComicInfo Format tag with the following values will force the issue to be treated as a special:
* TBD (Diesel to supply) - currently using existing list
- [x] Storyline tab will be removed from Series Detail. Issues will be the default tab. 
- [x] Volume tab will be hidden if there is only one Volume
- [x] Allow for non-numeric, negative, and 0 chapter/issue numbers
- [x] Covers will generate from issue 1 or greater (if 1 is missing) (#2432)
- [x] Ensure CBL Annuals work [(example)](https://github.com/DieselTech/CBL-ReadingLists/blob/main/Marvel/Characters/unsorted/Spider-Man/Spider-Man%20003%20(The%2080s).cbl) (See #2775 )
- [x] Set the Library Formats to just Archive by default
- [x] Ignore cover.ext files by default in the parser. 

### Annuals
- Annuals can be within a series or externally as their own series. The following occurs:
  - [x] If they are their own series, the main series will establish a relationship of Annual to the Annual Series. This will show under Related tab. (this is unfortunately not possible automatically and users will have to perform)
  - [x] If they are within the main series, they will be labelled as "Special". Annuals will be encouraged to be split for the future of this Library and integrations. 

### ComicInfo Tags
- [x] Add support to parse and display Imprint tag just like Publisher. This will bring same functionality like Filtering on it.
- [x] Team
- [x] Location

### Non-Number Issues
- [x] Issues will have a Sort Order field going forward. This will map with `<IssueOrder>` tag in ComicInfo. If not present, the issue number will be taken (if it is a number). Otherwise, will fallback to Issue number (`<Number>`). [ComicInfo Enhancement Request](https://github.com/anansi-project/comicinfo/issues/58)
- [x] Non-numeric issues will be grouped at the start or end (given an arbitrary number). 
- [x] (Stretch) Attempt to parse 18.HU -> 18 or 18.5
- Admin will be able to edit the non-numberic issue order via ComicInfo or via the UI (This may be pending until the UX refresh)

### Tachiyomi
- This will cause a breakage to Tachiyomi's GetLatestChapter API due to DefaultVolume/Chapter change. 

### CDisplayEx
- Need to validate with Henri if this will impact his app. (Validated, Henri will update, need to give a few weeks for testing and support)

Initial Estimate for time to deliver: 200 dev hours

# Tests
- [x] BasicParser
- [x] ComicVineParser
- [x] ImageParser
- [x] PdfParser
- [x] BookParser (not sure how to implement tests as it relies on actual epub parsing pretty heavily)

# Side Stuff noticed during development
- [x] Annual Series Relationship needs to be put on the wiki/wiki2
- [x] Need to tweak the Issue names (series detail) - preferring title doesn't look good. Needs to be tweaked until new UX
- [x] Test converting old Comic library to ComicVine

**Comment by majora2007** [comment]
Linked discussion: 
https://github.com/Kareadita/Kavita/discussions/2542

**Comment by XyberDAWG** [comment]
All of this would vastly improve the overall experience with Western Comics!

**Comment by Tomomatoes** [comment]
Would the changes to annuals allow them to be picked up by imported reading lists? 

"(Stretch) Attempt to parse 18.HU -> 18 or 18.5" - This would need to be 18.5 as there is an issue 18 too and 18.HU isn't the only one.
The order is 16, 16.HU, 17, 18, 18.HU, 19, 19.HU, 20, 20,HU. There is also 92.BEY. It would be awesome if you can parse them, if not the `<issue order>` tag seems like it would still solve the probelm.

**Comment by maximo1984** [comment]
Just started using Kavita for comics. I support the above features. I would also like to request an ability to add collections to collections. This would allow a higher level of organization. For example, creating many collections for various genres (super-hero, western, horror, etc), then adding all of those collections to a higher level collection simply titled "Genres"

**Comment by maximo1984** [comment]
Can I make some suggestions here? A couple things off top of my head now that I've started using this.

1. A feature to add single issues to collections, right now, can only add them to reading lists. One application for this would be creating a collection of favorite artists and all their issues drawn. I guess 'reading list' could be used for this, but I think collection is better suited.
2. Ability to search for creators inside single issues. Right now, it only finds the set/volume/etc. This is problematic for larger comic sets.

**Comment by majora2007** [comment]
The foundational changes are now in place (and extended testing has begun). This story is now ready to be started.

**Comment by majora2007** [comment]
Testing Issue:
- [x] Library Type pipe is missing for ComicVine
- [x] Cover Image isn't preferring Issue 1 when there is a 0 issue
- [x] Reading list page fails to open when item in ComicVine library

**Comment by XyberDAWG** [comment]
So from my testing, it divides all volumes into separate series. 

My directory setup is:

Dark Horse Comics
-Star Wars (1997)
--Volume 1997
--Volume 1998
Marvel
-Star Wars (1977)
--1977
--1979
-Star Wars (2015)
--Vol. 1
--Vol. 2

Tried three different Volume Folder formats to see if any work at grouping multiple Volumes
